version: 0.2
env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "https://console.aws.amazon.com/s3/buckets/applicationhosting/?region=us-east-1&tab=properties"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: 14
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started 
        - npm build 
artifacts:
    files:
        - '**/*'
    discard-paths: yes
